### ISSUE TITLE
Is understanding baseball part of the problem?

### ISSUE THREAD

**Issue by AB1908** [berkeley-cs186/sp20-proj1#4]
I spent several hours trying to understand baseball stats to solve 3i. Was this intended or is it just a byproduct of "not living in America"? Football (soccer) fan here.

**Comment by AB1908** [comment]
Addendum: Is there a reason 0.60000 is unacceptable as opposed to 0.6?

**Comment by ckw017** [comment]
Understanding a bit of baseball would be helpful, but you should be able to go off the formula in the wikipedia article without knowing. The H2B, H3B, and HR columns represent number of doubles, triples and homeruns. There is no column for singles, but the column H o f the batting table represents all hits = (# singles) + (# doubles) + (# triples) + (# home runs). You can use this information to get the number of singles.

I don't think we've ever had an issue the 0.600000 vs. 0.6 problem before (in general I believe Postgres will drop trailing 0's if they don't contribute any information).

**Comment by AB1908** [comment]
I see. Thanks for the clarification. I'm afraid the test script did fail me but changing the `DECIMAL` to a `FLOAT` did the trick.
